export const data = [
    {
        "id": "1",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "22",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc2-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "2",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "23",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc3-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "3",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "20",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc4-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "4",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "24",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc5-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "5",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "21",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc6-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "6",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "26",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc7-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "7",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "28",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc8-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "8",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "19",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc9-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "9",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "22",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc10-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    },
    {
        "id": "10",
        "upwork": "https://www.upwork.com/freelancers/~01c7617b97273ae1a1",
        "ndesign": "",
        "fiverr": "",
        "pph": "",
        "freelancer": "",
        "dhill": "",
        "other_platform": "",
        "ptitle": "Full Stack Developer",
        "pdesc": "I am a full-stack developer mainly skilled with Python, AWS, and React. I can make things work. I am a very fast learner and team player. I am currently working with a company in the Automotive Industry and creating value for many of my clients. Here I am available for the part-time hustle, and I can help you to solve your problem with my skills.",
        "pskill": "AWS",
        "sskill": "Azure",
        "pexp": "5",
        "fexp": "5",
        "state": "1",
        "city": "1",
        "phcharge": "30",
        "avail": "1",
        "delmode": "1",
        "profile_slug": "1eec440f-48ff-64f2-b076-9635a79ce702",
        "user_slug": "1eec43ac-bdc11-6217-baed-d57f40d56fac",
        "created_date": "2024-02-05 16:09:35.509016",
        "user_profile_pic": "profile.png",
        "full_name": "Sumanta Sharma",
        "country_id": "1",
        "country_name": "India",
        "city_name": "Bengaluru",
        "state_name": "Karnataka",
        "avail_name": "Available Immediately",
        "del_name": "24 hours turnaround"
    }
];
